Django_Jobs/urls.py
from django.conf.urls import url, include # include is a function
from django.contrib import admin
from django.urls import path, reverse_lazy

from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')), # include when we get to acc in our browser
    url(r'^', include('home.urls', namespace='home')),
    # its going to the account folder and urls file
    #url(r'^home/', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from . import views # . looks at all the files within the same level folder
from .forms import LoginForm, CustomPasswordResetForm, PasswordChange
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
PasswordChangeView,
PasswordResetView,
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView
) # will send e-mail
#passwordResetView sends e-mail

from home.views import HomeView


app_name='accounts'
urlpatterns = [
#subject_template_name='password_reset_subject.txt',success_url='/accounts/password_reset_done/',from_email='support@yoursite.ma'
    url(r'^$', HomeView.as_view(), name='home'), # you can put anything between the ^ and $ for ex: home
    url(r'^login/$', auth_views.LoginView.as_view(template_name = 'accounts/login.html', authentication_form=LoginForm), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name = 'accounts/logout.html'), name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name = 'edit_profile'),
    url(r'^profile/change-password/$', PasswordChangeView.as_view(template_name="accounts/change_password.html", form_class=PasswordChange, success_url=reverse_lazy('accounts:view_profile')), name='change_password'),
    #url(r'^profile/change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', PasswordResetView.as_view(template_name = 'accounts/reset_password.html', success_url=reverse_lazy('accounts:password_reset_done'), form_class=CustomPasswordResetForm, email_template_name ='accounts/reset_password_email.html'), name='reset_password'),



    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name ='accounts/reset_password_done.html'), name='password_reset_done'),
    #<uidb64>/<token>/
    #
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name ='accounts/reset_password_confirm.html',success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name = 'accounts/reset_password_complete.html'), name='password_reset_complete'),


]

home/urls.py
from django.conf.urls import url
from home.views import HomeView, result_view, bookmark, saved_jobs

app_name = 'home'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search-result', result_view, name="result"),
    url(r'^saved-jobs', saved_jobs, name="bookmark"),
    url(r'^mark', bookmark),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
'''
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='Long Beach')
'''



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #sort of like a foreign key
    description = models.CharField(max_length = 100, default ='')
    city = models.CharField(max_length = 100,default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    #image = models.ImageField(upload_to='profile_image',blank=True)
    # to upload image
    #long_beach = UserProfileManager()
    def __str__(self):
        return self.user.username



def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user = kwargs['instance'])
post_save.connect(create_profile, sender = User)

accounts/forms.py
# we gonna create django form for regiser page
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordResetForm, PasswordChangeForm




class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control py-2 border-right-0 border'}))

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs=({'class':'form-control py-2 border-right-0 border'})))
    password = forms.CharField(widget=forms.PasswordInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))

class RegistrationForm(UserCreationForm):
#UserCreationForm
# A form that creates a user, with no privileges, from the given username and password.
    email = forms.EmailField(required = True, widget=forms.EmailInput(
        attrs=({'class': 'form-control py-2 border-right-0 border'})))
    # make e-mail a required UserAttributeSimilarityValidator
    username = forms.CharField(max_length=16, help_text='16 characters max. Letters, digits and @/./+/-/_ only', widget=forms.TextInput(
        attrs=({'class': 'form-control py-2 border-right-0 border'})))
    first_name = forms.CharField(widget=forms.TextInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))
    last_name = forms.CharField(widget=forms.TextInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
    def save(self, commit = True):
        #prevents user from entering sql or harmful data
        user = super(RegistrationForm, self).save(commit = False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    username = forms.CharField(max_length = 16, help_text='16 characters max. Letters, digits and @/./+/-/_ only')
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
            'password'
        )

class PasswordChange(PasswordChangeForm):
    old_password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control py-2 border-right-0 border'}))
    new_password1 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control py-2 border-right-0 border'}))
    new_password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control py-2 border-right-0 border'}))

accounts/views.py
from django.shortcuts import render, redirect # render , renders html template
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm # form django has defined for us to render
from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
)                    #what is going to be a username & password field
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, login, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render
from django.views.generic import TemplateView
from django import forms


# Create your views here.xw
#@login_required() middleware replaces this

def register(request):
    form = RegistrationForm(request.POST)
    if request.method == 'POST': #sending data to web server and receiving
        if form.is_valid():
            form = form.save(commit=False)
            form = form.save()
            username = form.username
            password = form.password1
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('home:home'))
            else:
                pass
            return redirect(reverse('home:home'))
        else:
            pass
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/reg_form.html',args)
    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance = request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:# accounts for the get
        form = EditProfileForm(instance = request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data = request.POST, user = request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect('accounts:change_password')
    else:# accounts for the get
        form = PasswordChangeForm(user = request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

templates/accounts/change_password.html
{% extends 'base.html' %}

 <!-- anything here will override anything inside base.html blockhead -->

{% block title %}
Change Password
{% endblock %}

{% block content %}

  <!-- Portfolio Grid Section -->
    <div class="container" style="padding-top: 6rem; padding-bottom: 3rem">
        <div class="row">
            <div class="col-md-5 mx-auto">
                <div class="card text-white bg-info mx-auto">
                  <div class="card-header"><h3>Login</h3></div>
                  <div class="card-body">
                      <form method="post">{% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Old Password</b></p>
                                </blockquote>
                              <div class="input-group">
                                  {{ form.old_password }}
                                  <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-eye"></i></span>
                                    </div>
                                </div>
                                <div class="input-group">
                                  {{ form.errors.old_password }}
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>New Password</b></p>
                                </blockquote>
                                <div class="input-group">
                                  {{ form.new_password1 }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-eye"></i></span>
                                    </div>
                                </div>
                                <div class="input-group">
                                  {{ form.errors.new_password1 }}
                                </div>
                            </div>
                          </div>
                          <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Retype New Password</b></p>
                                </blockquote>
                                <div class="input-group">
                                  {{ form.new_password2 }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-eye"></i></span>
                                    </div>
                                </div>
                                <div class="input-group">
                                  {{ form.errors.new_password2 }}
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                              <button class="btn btn-success col-12"><b>Save</b></button>
                            </div>
                        </div>
                          <input type="hidden" name="next" value="{% url 'accounts:view_profile' %}">
                      </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block contents %}
<div class="container">

    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" name="button">Submit</button>
    </form>



</div>


{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

 <!-- anything here will override anything inside base.html blockhead -->

{% block title %}
Profile
{% endblock %}

{% block content %}
    <div class="container" style="padding-top: 6rem; padding-bottom: 3rem">
        <div class="row">
            <div class="col-md-9 mx-auto">
                <div class="row">
                <div class="col-md-4">
                    <h3>Email</h3>
                    <p>{{ request.user.email }}</p>
                </div>
                <div class="col-md-4" style="color: blue">
                    <p>Change email address</p>
                </div>
            </div>
                <div class="row">
                    <div class="col-md-4">
                        <h3>Password</h3>
                        <p>**********</p>
                    </div>
                    <div class="col-md-4" style="color: blue">
                        <p>Change password</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <h3>Phone</h3>
                        <p>{{ request.user.userprofile.phone }}</p>
                    </div>
                    <div class="col-md-4" style="color: blue">
                        {% if request.user.userprofile.phone %}
                            <p>Change phone number</p>
                        {% else %}<p>Add phone number</p>
                        {% endif %}
            </div>
        </div>
            </div>
        </div>

    </div>
{% endblock %}
{% block body %}
<div class="container">

    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" name="button">Submit</button>
    </form>



</div>


{% endblock %}

templates/accounts/login.html
{% extends 'base.html'%}

{% block title %}Login{% endblock %}

{% block content %}

  <!-- Portfolio Grid Section -->
    <div class="container" style="padding-top: 6rem; padding-bottom: 3rem">
        <div class="row">
            <div class="col-md-5 mx-auto">
                <div class="card text-white bg-info mx-auto">
                  <div class="card-header"><h3>Login</h3></div>
                  <div class="card-body">
                      <form method="post">{% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Username</b></p>
                                </blockquote>
                              <div class="input-group">
                                  {{ form.username }}
                                  <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                                    </div>
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Password</b></p>
                                </blockquote>
                                <div class="input-group">
                                  {{ form.password }}
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-eye"></i></span>
                                    </div>
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                  <div class="form-check">
                                      <input class="form-check-input" type="checkbox" name="exampleRadios" id="exampleRadios1">
                                      <label class="form-check-label" for="exampleRadios1">
                                        Keep me signed in
                                      </label>
                                  </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                              <button class="btn btn-success col-12"><b>Sign In</b></button>
                            </div>
                        </div>
                        <div class="form-row">
                        <div class="form-group col-md-12">
                          Don't have an account? Click <a href="{% url 'accounts:register' %}">here </a>to register
                        </div>
                    </div>
                          <input type="hidden" name="next" value="{% url 'home:home' %}">
                      </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block body %}
<div class="container">


<h1>Welcome</h1>
<p>
  You can log in here
</p>
<h2>Login</h2>
<form method = "post">
  {% csrf_token %}
  {{ form }} <!-- form as paragraph -->
<button type="submit" name="button"> Log In</button>
</form>
</div>
<!-- data that we're submitting through that form is secure -->
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html'%}


{% block body %}
<div class="container">


<h1>Logged Out</h1>
<p>
  You have successfully logged out!
</p>
</div>
<!-- data that we're submitting through that form is secure -->
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

 <!-- anything here will override anything inside base.html blockhead -->

{% block title %}
Profile
{% endblock %}

{% block content %}
    <div class="container" style="padding-top: 6rem; padding-bottom: 3rem">

        <div class="row">
            <div class="col-md-4">
                <label>User Id</label>
            </div>
            <div class="col-md-4">
                <p>{{ request.user }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label>First Name</label>
            </div>
            <div class="col-md-4">
                <p>{{ request.user.first_name }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label>Last Name</label>
            </div>
            <div class="col-md-4">
                <p>{{ request.user.last_name }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label>Email</label>
            </div>
            <div class="col-md-4">
                <p>{{ request.user.email }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label>Phone Number</label>
            </div>
            <div class="col-md-4">
                <p>{% if request.user.phone %}{{ request.user.phone }}{% else %}None{% endif %}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label>Password</label>
            </div>
            <div class="col-md-2">
                <p>******</p>
            </div>
            <div class="col-md-4">
                <a style="color: blue" href="{% url 'accounts:change_password' %}">Change Password</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label>Description</label>
            </div>
            <div class="col-md-4">
                <p>{{ request.user.description }}</p>
            </div>
        </div>
    </div>
{% endblock %}
{% block body %}

<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }} </p>
    <p>Email: {{ user.email }} </p>
    <!--<p>Description: {{ user.userprofile.description }}</p>-->
    <!--<p>Phone: {{ user.userprofile.phone}}</p>-->
    <!--<img src="{{ user.userprofile.image.url|default_if_none:'#' }}" width="240">-->

</div>


{% endblock %}

templates/accounts/reg_form.html
{% extends 'base.html' %}


{% block content %}

  <!-- Portfolio Grid Section -->
    <div class="container" style="padding-top: 6rem; padding-bottom: 3rem">
        <div class="row">
            <div class="col-md-5 mx-auto">
                <div class="card text-white bg-info mx-auto">
                  <div class="card-header"><h3>Register</h3></div>
                  <div class="card-body">
                      <form method="post">{% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Username</b></p>
                                </blockquote>
                              <div class="input-group">
                                  {{ form.username }}
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>First name</b></p>
                                </blockquote>
                                <div class="input-group">
                                  {{ form.first_name }}
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Last name</b></p>
                                </blockquote>
                                <div class="input-group">
                                  {{ form.last_name }}
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Email</b></p>
                                </blockquote>
                                <div class="input-group">
                                  {{ form.email }}
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Password</b></p>
                                </blockquote>
                                <div class="input-group">
                                  {{ form.password1 }}
                                </div>
                                <div class="input-group">{{ form.errors.password1 }}</div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Password Confirmation</b></p>
                                </blockquote>
                                <div class="input-group">
                                  {{ form.password2 }}
                                </div>
                                <div class="input-group">{{ form.errors.password2 }}</div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                              <button class="btn btn-success col-12"><b>Create Account</b></button>
                            </div>
                        </div>
                        <div class="form-row">
                        <div class="form-group col-md-12">
                          Already have an account? Click <a href="{% url 'accounts:login' %}">here </a>to login
                        </div>
                    </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block body %}
<div class="container">
<h1>Register</h1>
<form method="post">
  <!-- more secure of sending data through http protocol -->
  {% csrf_token %}
  {{ form.as_p }} <!-- render using paragraph -->
  <button type="submit" name="button">Submit</button>
</form>
</div>
{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html'%}


{% block content %}
<div class="container" style="padding-top: 6rem; padding-bottom: 3rem">
        <div class="row">
            <div class="col-md-5 mx-auto">
                <div class="card text-white bg-info mx-auto">
                  <div class="card-header"><h3>Reset Password</h3></div>
                  <div class="card-body">
                      <p>
                          Forgotten your password? <br>Enter your email address below,
                          and we'll email instructions for setting a new one.

                        </p>
                      <form method="post">{% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <blockquote class="blockquote text-left">
                                  <p class="mb-0"><b>Email</b></p>
                                </blockquote>
                              <div class="input-group">
                                  {{ form.email }}
                                  <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                                    </div>
                                </div>
                            </div>
                          </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                              <button class="btn btn-success col-12"><b>Reset Password</b></button>
                            </div>
                        </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block body %}
<div class="container">


<h1>Password Reset</h1>
<p>
  Forgotten your password? Enter your email address below,
  and we'll email instructions for setting a new one.

</p>
<h2>Login</h2>
<form method = "post">
  {% csrf_token %}
  {{ form.as_p }} <!-- form as paragraph -->
<button type="submit" name="button">Reset password</button>
</form>
</div>
<!-- data that we're submitting through that form is secure -->
{% endblock %}

templates/accounts/reset_password_complete.html
{% extends 'base.html'%}


{% block content %}

<div class="container" style="padding-top: 6rem; padding-bottom: 3rem">
    <div class="alert alert-primary" role="alert">
      <h4 class="alert-heading">Password reset complete</h4><hr>
      <p class="mb-0">Click to <a href="{% url 'accounts:login' %}">Log in</a></p>
    </div>
</div>
{% endblock %}

{% block body %}
<div class="container">


<h1>Password reset complete</h1>
<p>
</p>
<a href="{% url 'accounts:login' %}">Log in</a>
</div>
<!-- data that we're submitting through that form is secure -->
{% endblock %}

templates/accounts/reset_password_confirm.html
{% extends 'base.html'%}


{% block body %}
<div class="container">


<h1>Enter new password</h1>
<p>

</p>
<form method = "post">
  {% csrf_token %}
  {{ form.as_p }} <!-- form as paragraph -->
<button type="submit" name="button">Reset password</button>
</form>
</div>
<!-- data that we're submitting through that form is secure -->
{% endblock %}

templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}