Django_Jobs/urls.py
from django.conf.urls import url, include # include is a function
from django.contrib import admin
from django.urls import path, reverse_lazy

from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')), # include when we get to acc in our browser
    url(r'^', include('home.urls', namespace='home')),
    # its going to the account folder and urls file
    #url(r'^home/', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from . import views # . looks at all the files within the same level folder
from .forms import LoginForm, CustomPasswordResetForm, PasswordChange
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
PasswordChangeView,
PasswordResetView,
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView
) # will send e-mail
#passwordResetView sends e-mail

from home.views import HomeView


app_name='accounts'
urlpatterns = [
#subject_template_name='password_reset_subject.txt',success_url='/accounts/password_reset_done/',from_email='support@yoursite.ma'
    url(r'^$', HomeView.as_view(), name='home'), # you can put anything between the ^ and $ for ex: home
    url(r'^login/$', auth_views.LoginView.as_view(template_name = 'accounts/login.html', authentication_form=LoginForm), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name = 'accounts/logout.html'), name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name = 'edit_profile'),
    url(r'^profile/change-password/$', PasswordChangeView.as_view(template_name="accounts/change_password.html", form_class=PasswordChange, success_url=reverse_lazy('accounts:view_profile')), name='change_password'),
    #url(r'^profile/change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', PasswordResetView.as_view(template_name = 'accounts/reset_password.html', success_url=reverse_lazy('accounts:password_reset_done'), form_class=CustomPasswordResetForm, email_template_name ='accounts/reset_password_email.html'), name='reset_password'),



    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name ='accounts/reset_password_done.html'), name='password_reset_done'),
    #<uidb64>/<token>/
    #
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name ='accounts/reset_password_confirm.html',success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name = 'accounts/reset_password_complete.html'), name='password_reset_complete'),


]

home/urls.py
from django.conf.urls import url
from home.views import HomeView, result_view, bookmark, saved_jobs

app_name = 'home'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search-result', result_view, name="result"),
    url(r'^saved-jobs', saved_jobs, name="bookmark"),
    url(r'^mark', bookmark),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
'''
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='Long Beach')
'''



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #sort of like a foreign key
    description = models.CharField(max_length = 100, default ='')
    city = models.CharField(max_length = 100,default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    #image = models.ImageField(upload_to='profile_image',blank=True)
    # to upload image
    #long_beach = UserProfileManager()
    def __str__(self):
        return self.user.username



def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user = kwargs['instance'])
post_save.connect(create_profile, sender = User)

accounts/forms.py
# we gonna create django form for regiser page
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordResetForm, PasswordChangeForm




class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control py-2 border-right-0 border'}))

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs=({'class':'form-control py-2 border-right-0 border'})))
    password = forms.CharField(widget=forms.PasswordInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))

class RegistrationForm(UserCreationForm):
#UserCreationForm
# A form that creates a user, with no privileges, from the given username and password.
    email = forms.EmailField(required = True, widget=forms.EmailInput(
        attrs=({'class': 'form-control py-2 border-right-0 border'})))
    # make e-mail a required UserAttributeSimilarityValidator
    username = forms.CharField(max_length=16, help_text='16 characters max. Letters, digits and @/./+/-/_ only', widget=forms.TextInput(
        attrs=({'class': 'form-control py-2 border-right-0 border'})))
    first_name = forms.CharField(widget=forms.TextInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))
    last_name = forms.CharField(widget=forms.TextInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=({'class': 'form-control py-2 border-right-0 border'})))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
    def save(self, commit = True):
        #prevents user from entering sql or harmful data
        user = super(RegistrationForm, self).save(commit = False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    username = forms.CharField(max_length = 16, help_text='16 characters max. Letters, digits and @/./+/-/_ only')
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
            'password'
        )

class PasswordChange(PasswordChangeForm):
    old_password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control py-2 border-right-0 border'}))
    new_password1 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control py-2 border-right-0 border'}))
    new_password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control py-2 border-right-0 border'}))

accounts/views.py
from django.shortcuts import render, redirect # render , renders html template
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm # form django has defined for us to render
from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
)                    #what is going to be a username & password field
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, login, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render
from django.views.generic import TemplateView
from django import forms


# Create your views here.xw
#@login_required() middleware replaces this

def register(request):
    form = RegistrationForm(request.POST)
    if request.method == 'POST': #sending data to web server and receiving
        if form.is_valid():
            form = form.save(commit=False)
            form = form.save()
            username = form.username
            password = form.password1
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('home:home'))
            else:
                pass
            return redirect(reverse('home:home'))
        else:
            pass
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/reg_form.html',args)
    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance = request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:# accounts for the get
        form = EditProfileForm(instance = request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data = request.POST, user = request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect('accounts:change_password')
    else:# accounts for the get
        form = PasswordChangeForm(user = request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/base.html
<!-- included in every single page -->

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
    {% block head %}
    <!-- gives you a block space -->
    <title>Base</title>

    {% endblock %}
  </head>
  <body>
    <br><br><br>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/account">Job Hunter</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
      <!-- <ul class="nav navbar-nav"> --->
        <!-- { % url 'name' %} --->
        {% if user.is_authenticated %}
        &emsp;&emsp;
        <li><a href="{% url 'home:home' %}">Home</a> &emsp;&emsp; </li>
        <li><a href="{% url 'accounts:view_profile' %}">Profile</a> &emsp;&emsp;  </li>
        <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a> &emsp;&emsp;  </li>
        <li><a href="{% url 'accounts:change_password' %}">Change Password</a> &emsp;&emsp;</li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'accounts:logout' %}">Log Out</a> &emsp;&emsp;  </li>
        </ul>


        {% else %}
      <!-- <ul class="nav navbar-nav"> --->
        <ul class="nav navbar-nav">
          <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a> &emsp;&emsp;</li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            &emsp;&emsp;
            <li><a href="{% url 'accounts:register' %}">Register<span class="sr-only">(current)</span></a></li>
        </ul>
        {% endif %}

         </nav>





    {% block body %}

    {% endblock %}

  </body>
</html>