Django_Jobs/urls.py
from django.conf.urls import url, include # include is a function
from django.contrib import admin
from django.urls import path, reverse_lazy

from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')), # include when we get to acc in our browser
    url(r'^', include('home.urls', namespace='home')),
    # its going to the account folder and urls file
    #url(r'^home/', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from . import views # . looks at all the files within the same level folder
from .forms import LoginForm, CustomPasswordResetForm, PasswordChange
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
PasswordChangeView,
PasswordResetView,
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView
) # will send e-mail
#passwordResetView sends e-mail

from home.views import HomeView


app_name='accounts'
urlpatterns = [
#subject_template_name='password_reset_subject.txt',success_url='/accounts/password_reset_done/',from_email='support@yoursite.ma'
    url(r'^$', HomeView.as_view(), name='home'), # you can put anything between the ^ and $ for ex: home
    url(r'^login/$', auth_views.LoginView.as_view(template_name = 'accounts/login.html', authentication_form=LoginForm), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name = 'accounts/logout.html'), name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name = 'edit_profile'),
    url(r'^profile/change-password/$', PasswordChangeView.as_view(template_name="accounts/change_password.html", form_class=PasswordChange, success_url=reverse_lazy('accounts:view_profile')), name='change_password'),
    #url(r'^profile/change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', PasswordResetView.as_view(template_name = 'accounts/reset_password.html', success_url=reverse_lazy('accounts:password_reset_done'), form_class=CustomPasswordResetForm, email_template_name ='accounts/reset_password_email.html'), name='reset_password'),



    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name ='accounts/reset_password_done.html'), name='password_reset_done'),
    #<uidb64>/<token>/
    #
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name ='accounts/reset_password_confirm.html',success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name = 'accounts/reset_password_complete.html'), name='password_reset_complete'),


]

home/urls.py
from django.conf.urls import url
from home.views import HomeView, result_view, bookmark, saved_jobs

app_name = 'home'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search-result', result_view, name="result"),
    url(r'^saved-jobs', saved_jobs, name="bookmark"),
    url(r'^mark', bookmark),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Job Hunter | {% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Plugin CSS -->
  <link href="/static/vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="/static/css/freelancer.min.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav" style="border-bottom: solid white 2px">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'home:home' %}"><span class="badge badge-pill badge-warning" style="border-radius: 0; color: white">JH</span> Job Hunter</a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.resolver_match.view_name == 'home:home' %}active{% elif request.resolver_match.view_name == 'home:result' %}active{% endif %}" href="{% url 'home:home' %}">Home</a>
          </li>
        {% if request.user.is_authenticated %}
            <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.resolver_match.view_name == 'accounts:view_profile' %}active{% elif request.resolver_match.view_name == 'accounts:change_password' %}active{% endif %}" href="{% url 'accounts:view_profile' %}">Profile</a>
          </li>
            <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.resolver_match.view_name == 'home:bookmark' %}active{% endif %}" href="{% url 'home:bookmark' %}">Bookmark</a>
          </li>
            <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'accounts:logout' %}?next=/">Logout</a>
          </li>
        {% else %}
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.resolver_match.view_name == 'accounts:login' %}active{% endif %}" href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.resolver_match.view_name == 'accounts:register' %}active{% endif %}" href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>

{% block content %}
{% endblock %}

  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>
  <script src="/static/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="/static/js/jqBootstrapValidation.js"></script>
  <script src="/static/js/contact_me.js"></script>

  <!-- Custom scripts for this template -->

    {% block extra_js %}
    {% endblock %}

</body>

</html>